"""modification

Revision ID: 7bf8b56d316d
Revises: 02e84f219782
Create Date: 2021-10-06 11:03:42.903733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bf8b56d316d'
down_revision = '02e84f219782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('content', sa.String(), nullable=True))
    op.drop_column('todos', 'Content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('Content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('todos', 'content')
    # ### end Alembic commands ###
